### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

### ISSUE THREAD

**Issue by rozag** [Focus/latexer#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [latexer](https://github.com/Focus/latexer) package, v0.2.2
### Stack Trace

Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

```
At /usr/share/atom/resources/app/src/text-editor.js:1378

TypeError: Cannot read property 'getBufferPosition' of undefined
    at TextEditor.module.exports.TextEditor.getCursorBufferPosition (/usr/share/atom/resources/app/src/text-editor.js:1378:34)
    at /home/alexey/.atom/packages/latexer/lib/latexer.coffee:33:32
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
    at /usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1151:25
```
### Commands

```
     -1:50.7 core:save (atom-text-editor.editor.is-focused)
     -1:32.7 core:backspace (atom-text-editor.editor)
     -1:31.6 core:save (atom-text-editor.editor)
  3x -1:05.7 pdf-view:zoom-out (div.pdf-view)
     -1:02.4 pdf-view:zoom-in (div.pdf-view)
     -0:57.0 core:undo (atom-text-editor.editor.is-focused)
  2x -0:54.8 core:backspace (atom-text-editor.editor.is-focused)
     -0:51.2 core:save (atom-text-editor.editor.is-focused)
     -0:39.6 pdf-view:zoom-out (div.pdf-view)
     -0:38.4 pdf-view:zoom-in (div.pdf-view)
  4x -0:33.5 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -0:32.4 core:move-left (atom-text-editor.editor.is-focused)
  8x -0:31.5 core:backspace (atom-text-editor.editor.is-focused)
     -0:19.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.5 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.9 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-bibtex, v0.5.4
autocomplete-clang, v0.6.2
autocomplete-plus, v2.6.0
language-latex, v0.4.1
latex, v0.20.0
latexer, v0.2.2
pdf-view, v0.17.0

# Dev
No dev packages
```

**Comment by EtienneM** [comment]
Same problem here. It happened many times and the error keep showing up until I restart Atom. So it is a really annoying error...

I could not find any step to reproduce the error

**Comment by Focus** [comment]
When does it throw this error?

**Comment by rozag** [comment]
I really don't know. It was just like it looped.

ср, 22 апр. 2015, 15:49, Focus notifications@github.com:

**Comment by Focus** [comment]
I updated the package to version 0.2.3. It should hopefully fix this problem. If it's still an issue please submit a new bug report.
