### ISSUE TITLE
Not automatically adding .bib at the end of bibliography files

### ISSUE THREAD

**Issue by vladvelici** [Focus/latexer#2]
Assuming ref.bib exists, latex handles both the following cases fine while this plugin does not check if the file exists and then try the .bib as well.

\bibliography{ref}
\bibliography{ref.bib}

It's not a big issue but it worths being in the to-do list. I might send a pull request soon if that would be alright?

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [latexer](https://github.com/Focus/latexer) package, v0.2.2
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '[...hidden...]/ref'

```
At fs.js:519

Error: ENOENT: no such file or directory, open '[...hidden...]/ref'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at CiteView.module.exports.CiteView.getCitationsFromPath (/Users/vlad/.atom/packages/latexer/lib/cite-view.coffee:55:15)
  at CiteView.module.exports.CiteView.getCitations (/Users/vlad/.atom/packages/latexer/lib/cite-view.coffee:50:29)
  at CiteView.module.exports.CiteView.show (/Users/vlad/.atom/packages/latexer/lib/cite-view.coffee:18:14)
  at /Users/vlad/.atom/packages/latexer/lib/latexer.coffee:26:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1162:25

```
### Commands

```
     -0:15.0 core:confirm (atom-text-editor.editor.mini)
     -0:12.9 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:12.9 core:cancel (atom-text-editor.editor.mini)
     -0:11.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:09.3 core:save (atom-text-editor.editor.is-focused)
     -0:08.9 core:move-up (atom-text-editor.editor.is-focused)
     -0:06.2 core:move-down (atom-text-editor.editor.is-focused)
  4x -0:05.8 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.1 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:04.3 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:04.3 core:cancel (atom-text-editor.editor.mini)
  2x -0:03.9 autocomplete-plus:select-previous (atom-text-editor.editor.is-focused)
     -0:03.2 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
  2x -0:02.7 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:02.1 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.8 core:move-up (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.7.1
autocomplete-snippets, v1.2.0
gofmt, v0.2.0
language-latex, v0.4.1
latex, v0.20.0
latexer, v0.2.2

# Dev
No dev packages
```

**Comment by Focus** [comment]
Yes this is simple enough to fix. I missed this issue initially.

**Comment by Focus** [comment]
This is now fixed.
