### ISSUE TITLE
Cloned latexer package cannot find module atom-space-pen-views

### ISSUE THREAD

**Issue by yudai-nkt** [Focus/latexer#43]
I just forked this repository and cloned the forked one to submit a pull request. I encountered an error from `latexer` package.

``` zsh
$ apm uninstall latexer
$ cd ~/work/atom
$ git clone git@github.com:yudai-nkt/latexer.git
$ cd latexer
$ apm link .
$ atom . --dev
```

yield the error saying "Failed to activate the latexer package" with the following log.

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/yudai-nkt/.atom/packages/latexer/lib/label-view.coffee:1:22)
    at Object.<anonymous> (/Users/yudai-nkt/.atom/packages/latexer/lib/label-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/yudai-nkt/work/atom/latexer/lib/latexer.coffee:1:13)
    at Object.<anonymous> (/Users/yudai-nkt/work/atom/latexer/lib/latexer.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
```

I couldn't understand this error because both `apm`-installed `latexer` and the latest one on GitHub have the same dependencies written in `package.json`:

``` cson
"dependencies": {
  "atom-space-pen-views": "^2.0.0",
  "fs-plus": "^2.0.0"
}
```

Could you tell me how to handle this error?

My environment is:
- **OS**: OS X El Capitan 10.11.4
- **Atom**: Version 1.8.0
- **latexer**: 37b02cb62341620998a4eaf736537eac2ecd97c1

**Comment by Focus** [comment]
You need to run `apm install` after `cd latexer` which will install the dependencies.

**Comment by yudai-nkt** [comment]
Thanks, that addressed the problem.
